# Site settings
title: CHCS Governing Board
email: clay.johnson@chatthillscharter.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/governance/" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  facilities:
    output: true
  personnel:
    output: true
  finance:
    output: true
  records:
    output: true
    label: Data
  students:
    output: true
