# Site settings
title: CHCS Governing Board
email: clay.johnson@chatthillscharter.org
description: > # this means to ignore newlines until "baseurl:"
  The Chattahoochee Hills Charter School Governing Board Website.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  facilities:
    output: true
  personnel:
    output: true
  finance:
    output: true
  records:
    output: true
    label: Data
  students:
    output: true
  board:
    output: true
